"""
crear tablas permisos y relaciones

Revision ID: 0538266aae50
Revises: 3006e9d82f62
Create Date: 2026-07-23 17:05:00.558462
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0538266aae50'
down_revision: Union[str, None] = '3006e9d82f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("accion IN ('ver', 'listar', 'crear', 'editar', 'eliminar', 'exportar', 'importar', 'aprobar', 'anular')", name='ck_permisos_accion'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuario_permisos_override',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('permitido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'permiso_id')
    )
    op.create_index(op.f('ix_usuario_permisos_override_usuario_id'), 'usuario_permisos_override', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_usuario_permisos_override_permiso_id'), 'usuario_permisos_override', ['permiso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_permisos_override_permiso_id'), table_name='usuario_permisos_override')
    op.drop_index(op.f('ix_usuario_permisos_override_usuario_id'), table_name='usuario_permisos_override')
    op.drop_table('usuario_permisos_override')
    op.drop_table('rol_permisos')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
