"""
crear tabla marcas

Revision ID: 866045e608b1
Revises: a94e53c25741
Create Date: 2026-07-23 15:37:13.921469
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '866045e608b1'
down_revision: Union[str, None] = 'a94e53c25741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_marcas_id'), 'marcas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marcas_id'), table_name='marcas')
    op.drop_table('marcas')
    # ### end Alembic commands ###
