"""
crear tabla usuarios

Revision ID: 8ed23b6e5e84
Revises: 9d764eb806db
Create Date: 2026-07-23 16:26:36.792672
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8ed23b6e5e84'
down_revision: Union[str, None] = '9d764eb806db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('pin', sa.String(length=4), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'inactivo')", name='ck_usuarios_estado'),
    sa.CheckConstraint("rol IS NULL OR rol IN ('administrador', 'gestor', 'vendedor')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
