"""
crear tabla productos y relaciones

Revision ID: d4bdc436dec4
Revises: e623c40a83ff
Create Date: 2026-07-23 16:00:39.165343
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd4bdc436dec4'
down_revision: Union[str, None] = 'e623c40a83ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gestionar_inventario', sa.Boolean(), nullable=False),
    sa.Column('cantidad_disponible', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('producto_categoria',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_id')
    )
    op.create_table('producto_etiqueta',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'etiqueta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_etiqueta')
    op.drop_table('producto_categoria')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###
