"""
crear tabla movimientos_financieros

Revision ID: e5f6a7b1c2d3
Revises: d4e5f6a7b1c2
Create Date: 2026-07-23 20:30:00.000000
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e5f6a7b1c2d3'
down_revision: Union[str, None] = 'd4e5f6a7b1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_financieros',
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('concepto', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_financieros_id'), 'movimientos_financieros', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_financieros_id'), table_name='movimientos_financieros')
    op.drop_table('movimientos_financieros')
    # ### end Alembic commands ###
