"""
crear tabla etiquetas

Revision ID: e623c40a83ff
Revises: 866045e608b1
Create Date: 2026-07-23 15:39:48.700789
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e623c40a83ff'
down_revision: Union[str, None] = '866045e608b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiquetas',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_etiquetas_id'), 'etiquetas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etiquetas_id'), table_name='etiquetas')
    op.drop_table('etiquetas')
    # ### end Alembic commands ###
